-- MeSH do PubMed para os artigos que estavam sem (20/Ago/2026). Custo: zero.
-- Vazio e nulo sao a MESMA COISA (decisao do Dr. Eduardo): quem nao tem
-- descritor recebe '{}' e entra na proxima varredura, sem precisar saber por que.

BEGIN;
UPDATE artigos SET mesh_terms=ARRAY['Humans','Peripheral Arterial Disease','Lower Extremity','American Heart Association','United States','Cardiology','Societies, Medical']::text[] WHERE doc_id='10.1016/j.jacc.2024.02.013';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Female','Male','Cardiomyopathies','Aged','Single Photon Emission Computed Tomography Computed Tomography','Amyloid Neuropathies, Familial','Predictive Value of Tests','Reproducibility of Results','Myocardium','Radiopharmaceuticals','Technetium Tc 99m Pyrophosphate','Retrospective Studies','Aged, 80 and over','Middle Aged']::text[] WHERE doc_id='10.1161/CIRCIMAGING.126.019832';
UPDATE artigos SET mesh_terms=ARRAY['Adolescent','Child','Female','Humans','Behavior Therapy','Body Mass Index','Counseling','Pediatric Obesity','Primary Health Care','Referral and Consultation','Weight Loss','American Indian or Alaska Native','Hispanic or Latino','Black or African American','Poverty']::text[] WHERE doc_id='10.1001/jama.2024.11146';
UPDATE artigos SET mesh_terms=ARRAY['Adult','Aged','Female','Humans','Male','Middle Aged','Biomarkers','Blood Urea Nitrogen','C-Reactive Protein','Cause of Death','Erythrocyte Indices','Follow-Up Studies','Heart Failure','Lymphocytes','Nutrition Surveys','Predictive Value of Tests','Prognosis','Retrospective Studies','Risk Assessment','Risk Factors','Serum Albumin','Serum Albumin, Human','Survival Rate','United States']::text[] WHERE doc_id='10.1002/clc.70401';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Defects, Congenital','Adult','Cardiology','United States','American Heart Association','Disease Management','Practice Guidelines as Topic']::text[] WHERE doc_id='10.1016/j.jacc.2025.09.006';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Female','Retrospective Studies','Renal Dialysis','Hypertension, Pulmonary','Male','Middle Aged','Risk Factors','Risk Assessment','Echocardiography','Cause of Death','China','Kidney Failure, Chronic','Survival Rate','Follow-Up Studies','Prognosis','Arteriovenous Shunt, Surgical','Time Factors']::text[] WHERE doc_id='10.1002/clc.70415';
UPDATE artigos SET mesh_terms=ARRAY['Coronary Angiography','Coronary Artery Disease','Coronary Stenosis','Coronary Vessels','Humans','Myocardial Infarction']::text[] WHERE doc_id='10.1093/ehjacc/zuab049';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Myocardial Infarction','United States','Male','Female','Hypertension','Databases, Factual','Aged','Middle Aged','Essential Hypertension','Centers for Disease Control and Prevention, U.S.','Adult','Cause of Death','Risk Factors','Survival Rate','Time Factors']::text[] WHERE doc_id='10.1002/clc.70420';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Female','Humans','Male','Middle Aged','Aspirin','Clopidogrel','Coronary Circulation','Drug Therapy, Combination','Emergency Medical Services','Fibrinolytic Agents','Follow-Up Studies','Heparin','Incidence','Myocardial Reperfusion','Percutaneous Coronary Intervention','Platelet Aggregation Inhibitors','Prospective Studies','Purinergic P2Y Receptor Antagonists','ST Elevation Myocardial Infarction','Ticagrelor','Time Factors','Treatment Outcome']::text[] WHERE doc_id='10.1002/clc.70418';
UPDATE artigos SET mesh_terms=ARRAY['Humans','PCSK9 Inhibitors','Female','Male','Aged','Atherosclerosis','Middle Aged','Cholesterol, LDL','Treatment Outcome','Anticholesteremic Agents','Antibodies, Monoclonal','Antibodies, Monoclonal, Humanized','Myocardial Infarction','Proprotein Convertase 9','Ischemic Stroke']::text[] WHERE doc_id='10.1093/eurheartj/ehag176';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Photoplethysmography','Heart Failure','Female','Male','ROC Curve','Aged','Predictive Value of Tests','Cardiac Output','Middle Aged','Posture','Area Under Curve','Natriuretic Peptide, Brain','Biomarkers','Risk Factors','Peptide Fragments']::text[] WHERE doc_id='10.1002/clc.70400';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Cardiac Resynchronization Therapy','Heart Failure','Female','Male','Prospective Studies','Stroke Volume','Treatment Outcome','Aged','Ventricular Function, Left','Predictive Value of Tests','Time Factors','Bundle-Branch Block','Activities of Daily Living','Risk Factors','Middle Aged','Follow-Up Studies','Recovery of Function','Multivariate Analysis']::text[] WHERE doc_id='10.1002/clc.70389';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Mucocutaneous Lymph Node Syndrome','Female','Japan','Pregnancy','Child, Preschool','Male','Infant','Risk Factors','Reproductive Techniques, Assisted','Prospective Studies','Adult','Cohort Studies','Infant, Newborn']::text[] WHERE doc_id='10.1001/jamanetworkopen.2026.28586';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart-Assist Devices','Female','Retrospective Studies','Male','Heart Failure','Middle Aged','Practice Guidelines as Topic','Follow-Up Studies','Survival Rate','Adrenergic beta-Antagonists','Ventricular Function, Left']::text[] WHERE doc_id='10.1093/eschf/xvag174';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Atrial Fibrillation','Ethanol','Treatment Outcome','Catheter Ablation','Animals','Heart Rate','Coronary Vessels']::text[] WHERE doc_id='10.1002/clc.70398';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Myocardial Infarction','Male','Incidence','Middle Aged','Female','United Kingdom','Aged','Risk Assessment','Risk Factors','Follow-Up Studies','Biomarkers','Prognosis']::text[] WHERE doc_id='10.1093/eschf/xvag187';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Female','Retrospective Studies','Prognosis','Male','Amyloid Neuropathies, Familial','Cardiomyopathies','Exercise Test','Heart Rate','Aged','Follow-Up Studies','Exercise Tolerance']::text[] WHERE doc_id='10.1093/eschf/xvag170';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Female','Male','Pulmonary Artery','Ventricular Function, Right','Stroke Volume','Follow-Up Studies','Heart Ventricles','Heart Atria','Echocardiography','Aged','Middle Aged']::text[] WHERE doc_id='10.1093/eschf/xvag180';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Female','France','Prognosis','Phenotype','Male','Genotype','Middle Aged','Apical Hypertrophic Cardiomyopathy','Cohort Studies','Echocardiography','Magnetic Resonance Imaging, Cine','Risk Assessment','Global Longitudinal Strain','Mutation','Genetic Testing','Survival Analysis','Cardiomyopathy, Hypertrophic','Aged','Severity of Illness Index','Follow-Up Studies']::text[] WHERE doc_id='10.1093/ehjci/jeag141';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Defibrillators, Implantable','Pacemaker, Artificial','Remote Patient Monitoring','Arrhythmias, Cardiac','Telemedicine','Digital Health']::text[] WHERE doc_id='10.1161/CIRCEP.125.014786';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Circadian Rhythm','Blood Pressure','Male','Female','Percutaneous Coronary Intervention','Prognosis','Blood Pressure Monitoring, Ambulatory','ST Elevation Myocardial Infarction','Risk Factors','Middle Aged','Anterior Wall Myocardial Infarction','Time Factors','Follow-Up Studies','Retrospective Studies','Treatment Outcome','Aged']::text[] WHERE doc_id='10.1002/clc.70377';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Female','Male','Cardiovascular Diseases','Healthy Lifestyle','Middle Aged','Metabolic Syndrome','Prospective Studies','United Kingdom','Risk Factors','Cause of Death','Aged','United States','Kidney Diseases','Follow-Up Studies','Risk Assessment','Survival Rate','UK Biobank','Sedentary Behavior','Exercise','Nutrition Surveys']::text[] WHERE doc_id='10.1002/clc.70436';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Tirzepatide','Propensity Score','Female','Heart Failure','Retrospective Studies','Stroke Volume','Male','Aged','Recombinant Fusion Proteins','Glucagon-Like Peptides','Immunoglobulin Fc Fragments','Treatment Outcome','Middle Aged']::text[] WHERE doc_id='10.1002/clc.70441';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Myocardial Bridging','Female','Male','Angina Pectoris','Middle Aged','Treatment Outcome','Quality of Life','Aged','Prospective Studies','Coronary Angiography','Echocardiography, Stress','Follow-Up Studies']::text[] WHERE doc_id='10.1093/eurheartj/ehag373';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Aortic Valve Stenosis','Stroke Volume','Ventricular Function, Left','Prognosis','Risk Factors']::text[] WHERE doc_id='10.1161/CIRCHEARTFAILURE.126.014249';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Cost-Benefit Analysis','Cost-Effectiveness Analysis','Male','Female','Endovascular Procedures','Quality-Adjusted Life Years','Aged','United States','Chronic Limb-Threatening Ischemia','Ischemia','Vascular Surgical Procedures','Markov Chains','Chronic Disease']::text[] WHERE doc_id='10.1001/jamanetworkopen.2026.27335';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Tirzepatide','Biomarkers','Cardiovascular Diseases','Male','Female','Obesity','Middle Aged','Heart Disease Risk Factors','Double-Blind Method','Diabetes Mellitus, Type 2','Time Factors']::text[] WHERE doc_id='10.1016/j.jacc.2026.04.044';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Sarcopenia','Obesity','Heart Failure','Female','Male','Muscle, Skeletal','Genome-Wide Association Study','Magnetic Resonance Imaging, Cine']::text[] WHERE doc_id='10.1016/j.jacc.2026.05.022';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Cardiovascular Diseases','Body Mass Index','Waist-Hip Ratio','Female','Waist Circumference','Male','Middle Aged','Cohort Studies','Risk Assessment','Aged','Obesity','Prognosis']::text[] WHERE doc_id='10.1016/j.jacc.2026.05.050';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Female','Stroke','Middle Aged','Risk Factors','Primary Prevention','Male','Aged','Telemedicine','Mobile Applications','Prospective Studies','Australia','New Zealand','Exercise']::text[] WHERE doc_id='10.1161/STROKEAHA.125.054001';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Thrombectomy','Female','Male','Blood Pressure','Endovascular Procedures','Treatment Outcome','Aged','Ischemic Stroke','Middle Aged','Antihypertensive Agents','Prospective Studies','Stroke','Brain Ischemia','Follow-Up Studies','Republic of Korea']::text[] WHERE doc_id='10.1161/STROKEAHA.126.055632';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Aged','Female','Male','Cerebral Hemorrhage','Platelet Aggregation Inhibitors','Fibrinolytic Agents','Aged, 80 and over','Treatment Outcome','Recurrence','Ischemic Stroke']::text[] WHERE doc_id='10.1161/STROKEAHA.125.054990';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Tirofiban','Female','Male','Middle Aged','Intracranial Aneurysm','Endovascular Procedures','Aged','Thromboembolism','Platelet Aggregation Inhibitors','Adult','Prospective Studies','Treatment Outcome','Stroke']::text[] WHERE doc_id='10.1161/STROKEAHA.126.056558';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Diabetes Mellitus, Type 2','Female','Middle Aged','Medicaid','Male','United States','Glycated Hemoglobin','Glycemic Control','Blood Glucose','Adult','Food Security','California']::text[] WHERE doc_id='10.1161/CIRCULATIONAHA.125.077982';
UPDATE artigos SET mesh_terms=ARRAY['American Heart Association','Anti-Arrhythmia Agents','Arrhythmias, Cardiac','Athletes','Autopsy','Cardiovascular Diseases','Catheter Ablation','Comorbidity','Death, Sudden, Cardiac','Defibrillators','Female','Humans','Pregnancy','Primary Prevention','Quality of Life','Renal Insufficiency, Chronic','Secondary Prevention','Sex Factors','Terminal Care','United States']::text[] WHERE doc_id='10.1016/j.jacc.2017.10.054';
UPDATE artigos SET mesh_terms=ARRAY['American Heart Association','Cardiology','Coronary Artery Disease','Humans','Myocardial Revascularization','United States']::text[] WHERE doc_id='10.1016/j.jacc.2021.09.006';
UPDATE artigos SET mesh_terms=ARRAY['United States','Humans','Proliferating Cell Nuclear Antigen','American Heart Association','Heart Diseases','Cardiology','Myocardial Ischemia','Chronic Disease','Coronary Disease']::text[] WHERE doc_id='10.1016/j.jacc.2023.04.003';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Stroke Volume','Animals','Veins','Endothelium, Vascular','Ventricular Function, Left','Vasodilation','Endothelium-Dependent Relaxing Factors']::text[] WHERE doc_id='10.1093/ehjcvp/pvag024';
UPDATE artigos SET mesh_terms=ARRAY['Humans','United States','Atrial Fibrillation','American Heart Association','Cardiology','Thromboembolism','Risk Factors']::text[] WHERE doc_id='10.1016/j.jacc.2023.08.017';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Perioperative Care','Cardiovascular Diseases','United States','American Heart Association','Surgical Procedures, Operative','Cardiology']::text[] WHERE doc_id='10.1016/j.jacc.2024.06.013';
UPDATE artigos SET mesh_terms=ARRAY['Cardiomyopathy, Hypertrophic','Humans','United States','American Heart Association','Cardiology','Disease Management']::text[] WHERE doc_id='10.1016/j.jacc.2024.02.014';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Medical Futility','Aged','Heart Diseases','Decision Making','Frailty','Palliative Care','Frail Elderly']::text[] WHERE doc_id='10.1093/eurheartj/ehaf351';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Magnetic Resonance Imaging, Cine','Fetal Heart','Female','Pregnancy','Prenatal Diagnosis','Predictive Value of Tests','Heart Defects, Congenital','Reproducibility of Results']::text[] WHERE doc_id='10.1161/CIRCIMAGING.126.019755';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Male','Female','Natriuretic Peptide, Brain','Diuretics','Acute Disease','Peptide Fragments','Aged','Middle Aged','Biomarkers','Drug Resistance']::text[] WHERE doc_id='10.1016/j.ahj.2026.107510';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Female','Male','Middle Aged','Triage','Aged','Case-Control Studies','California','Predictive Value of Tests','Oregon','Death, Sudden, Cardiac','Machine Learning','Risk Factors','Dyspnea','Chest Pain','Risk Assessment','Prognosis','Heart Failure','Reproducibility of Results']::text[] WHERE doc_id='10.1161/CIRCEP.125.014647';
UPDATE artigos SET mesh_terms=ARRAY['Adrenergic beta-Antagonists','Carbazoles','Carvedilol','Chronic Disease','Disease-Free Survival','Double-Blind Method','Health Resources','Heart Failure','Hospitalization','Humans','Propanolamines','Risk','Survival Rate']::text[] WHERE doc_id='10.1161/01.CIR.0000035653.72855.BF';
UPDATE artigos SET mesh_terms=ARRAY['Adrenergic beta-Antagonists','Aged','Benzopyrans','Ethanolamines','Heart Failure','Humans','Nebivolol','Randomized Controlled Trials as Topic']::text[] WHERE doc_id='10.1093/eurheartj/ehi118';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Cardiac Pacing, Artificial','Defibrillators, Implantable','Double-Blind Method','Electrocardiography','Female','Heart Failure','Hospitalization','Humans','Intention to Treat Analysis','Kaplan-Meier Estimate','Male','Middle Aged','Severity of Illness Index','Ventricular Dysfunction, Left']::text[] WHERE doc_id='10.1056/NEJMoa1009540';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Practice Guidelines as Topic','Stroke Volume','Randomized Controlled Trials as Topic','Ventricular Function, Left']::text[] WHERE doc_id='10.1093/eschf/xvag141';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Cardiovascular Agents','Cardiovascular Diseases','Combined Modality Therapy','Defibrillators, Implantable','Double-Blind Method','Eplerenone','Female','Follow-Up Studies','Heart Failure','Hospitalization','Humans','Kaplan-Meier Estimate','Male','Middle Aged','Mineralocorticoid Receptor Antagonists','Proportional Hazards Models','Spironolactone']::text[] WHERE doc_id='10.1056/NEJMoa1009492';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Cognitive Dysfunction','Prognosis','Risk Factors','Global Health']::text[] WHERE doc_id='10.1093/eschf/xvag192';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Pacemaker, Artificial','Tricuspid Valve Insufficiency','Cardiac Pacing, Artificial','Equipment Design']::text[] WHERE doc_id='10.1002/clc.70413';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Developing Countries','Health Services Accessibility','India','Nicotine Replacement Therapy','Smoking Cessation','Tobacco Control','Tobacco Industry','Tobacco Use Cessation','Vietnam','Tobacco Use','Cost-Effectiveness Analysis','Advertising']::text[] WHERE doc_id='10.1056/NEJMra2507061';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Ventricular Dysfunction, Left','American Heart Association','Anticoagulants','Ischemic Stroke','United States','Thrombosis','Risk Factors','Platelet Aggregation Inhibitors','Disease Management','Stroke']::text[] WHERE doc_id='10.1161/STR.0000000000000528';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Coronary Vessel Anomalies','Terminology as Topic','Consensus','Predictive Value of Tests','International Cooperation','Delphi Technique','Coronary Angiography','Prognosis','Risk Factors','Coronary Vessels','Risk Assessment']::text[] WHERE doc_id='10.1016/j.jcmg.2026.02.005';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Coronary Artery Disease','Double-Blind Method','Drug Therapy, Combination','Factor Xa Inhibitors','Female','Follow-Up Studies','Heart Failure','Humans','Kaplan-Meier Estimate','Male','Middle Aged','Myocardial Infarction','Natriuretic Peptide, Brain','Patient Readmission','Platelet Aggregation Inhibitors','Rivaroxaban','Stroke','Stroke Volume','Treatment Failure']::text[] WHERE doc_id='10.1056/NEJMoa1808848';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Benzhydryl Compounds','Cardiovascular Diseases','Diabetes Mellitus, Type 2','Disease Progression','Double-Blind Method','Female','Glomerular Filtration Rate','Glucosides','Heart Failure','Hospitalization','Humans','Male','Middle Aged','Proportional Hazards Models','Renal Insufficiency, Chronic','Sodium-Glucose Transporter 2 Inhibitors','Stroke Volume']::text[] WHERE doc_id='10.1056/NEJMoa2022190';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Aged, 80 and over','Cardiac Myosins','Cardiotonic Agents','Cardiovascular Diseases','Female','Heart Failure, Systolic','Humans','Male','Middle Aged','Myocardial Contraction','Stroke Volume','Urea']::text[] WHERE doc_id='10.1056/NEJMoa2025797';
UPDATE artigos SET mesh_terms=ARRAY['Adult','Benzhydryl Compounds','Cardiovascular Diseases','Chronic Disease','Double-Blind Method','Female','Glucosides','Heart Failure','Hospitalization','Humans','Male','Sodium-Glucose Transporter 2 Inhibitors','Stroke Volume']::text[] WHERE doc_id='10.1056/NEJMoa2107038';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Ischemic Stroke','American Heart Association','United States','Thrombolytic Therapy','Endovascular Procedures','Disease Management','Thrombectomy','Brain Ischemia']::text[] WHERE doc_id='10.1161/STR.0000000000000513';
UPDATE artigos SET mesh_terms=ARRAY['Benzhydryl Compounds','Diabetes Mellitus, Type 2','Glucosides','Heart Failure','Humans','Sodium-Glucose Transporter 2 Inhibitors','Stroke Volume','Ventricular Function, Left']::text[] WHERE doc_id='10.1056/NEJMoa2206286';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Female','Humans','Male','Middle Aged','Body Mass Index','Cardiovascular Diseases','Double-Blind Method','Glucagon-Like Peptide 1','Heart Failure','Kaplan-Meier Estimate','Obesity','Quality of Life','Stroke Volume','Tirzepatide','Follow-Up Studies','Treatment Outcome']::text[] WHERE doc_id='10.1056/NEJMoa2410027';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Female','Humans','Male','Middle Aged','Double-Blind Method','Follow-Up Studies','Heart Failure','Hospitalization','Kaplan-Meier Estimate','Mineralocorticoid Receptor Antagonists','Naphthyridines','Stroke Volume','Aged, 80 and over','Treatment Outcome']::text[] WHERE doc_id='10.1056/NEJMoa2407107';
UPDATE artigos SET mesh_terms=ARRAY['Adrenergic beta-Antagonists','Aged','Angiotensin II Type 1 Receptor Blockers','Angiotensin-Converting Enzyme Inhibitors','Biphenyl Compounds','Cardiovascular Diseases','Drug Therapy, Combination','Female','Follow-Up Studies','Heart Failure','Hospitalization','Humans','Irbesartan','Kaplan-Meier Estimate','Male','Middle Aged','Proportional Hazards Models','Quality of Life','Stroke Volume','Tetrazoles','Treatment Failure']::text[] WHERE doc_id='10.1056/NEJMoa0805450';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Female','Platelet Aggregation Inhibitors','Blood Platelets','Animals','Male','Thrombosis','Sex Characteristics','Platelet Activation','Sex Factors','Hemostasis']::text[] WHERE doc_id='10.1161/CIRCRESAHA.126.328602';
UPDATE artigos SET mesh_terms=ARRAY['Humans','No-Reflow Phenomenon','Percutaneous Coronary Intervention','ST Elevation Myocardial Infarction','Microcirculation','Coronary Circulation','Myocardial Reperfusion','Heart Failure','Thrombectomy']::text[] WHERE doc_id='10.1093/eurheartj/ehag334';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Bundle of His','Bundle-Branch Block','Cardiac Pacing, Artificial','Cardiac Resynchronization Therapy','Heart Failure','Stroke Volume','Cardiac Resynchronization Therapy Devices','Randomized Controlled Trials as Topic']::text[] WHERE doc_id='10.1056/NEJMra2415650';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Cardiac Pacing, Artificial','Defibrillators, Implantable','Disease-Free Survival','Electric Countershock','Female','Heart Failure','Humans','Kaplan-Meier Estimate','Male','Middle Aged','Pacemaker, Artificial','Stroke Volume']::text[] WHERE doc_id='10.1056/NEJMoa0906431';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Anemia, Iron-Deficiency','Chronic Disease','Female','Ferric Compounds','Ferritins','Follow-Up Studies','Heart Failure','Hematinics','Humans','Iron Deficiencies','Male','Maltose','Quality of Life','Stroke Volume','Ventricular Dysfunction, Left']::text[] WHERE doc_id='10.1056/NEJMoa0908355';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Female','Fructose','Hypertension','Child','Prospective Studies','Male','Sugar-Sweetened Beverages','Risk Factors','Adolescent','Fruit and Vegetable Juices','Adult','Beverages','Longitudinal Studies','Young Adult','Fruit','Incidence']::text[] WHERE doc_id='10.1161/CIRCULATIONAHA.125.077666';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Rupture, Post-Infarction','Aneurysm, False','Papillary Muscles','Myocardial Infarction','Heart Aneurysm','Recurrence','Myocardial Revascularization']::text[] WHERE doc_id='10.1093/eurheartj/ehag164';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Cardiovascular Diseases','Combined Modality Therapy','Coronary Artery Bypass','Coronary Artery Disease','Female','Heart Failure','Hospitalization','Humans','Intention to Treat Analysis','Kaplan-Meier Estimate','Male','Middle Aged','Proportional Hazards Models','Ventricular Dysfunction, Left']::text[] WHERE doc_id='10.1056/NEJMoa1100356';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Aged, 80 and over','Combined Modality Therapy','Female','Heart Failure','Heart Valve Prosthesis','Heart Valve Prosthesis Implantation','Hospitalization','Humans','Intention to Treat Analysis','Kaplan-Meier Estimate','Male','Middle Aged','Mitral Valve','Mitral Valve Insufficiency','Percutaneous Coronary Intervention','Prosthesis Failure','Stroke Volume','Treatment Outcome','Ventricular Dysfunction, Left']::text[] WHERE doc_id='10.1056/NEJMoa1806640';
UPDATE artigos SET mesh_terms=ARRAY['Adolescent','Adult','Aged','Aged, 80 and over','Disease-Free Survival','Female','Heart Failure','Heart-Assist Devices','Humans','Intention to Treat Analysis','Kaplan-Meier Estimate','Male','Middle Aged','Prosthesis Design','Prosthesis Failure','Reoperation','Stroke']::text[] WHERE doc_id='10.1056/NEJMoa1900486';
UPDATE artigos SET mesh_terms=ARRAY['Benzhydryl Compounds','Diabetes Mellitus, Type 2','Double-Blind Method','Glucosides','Heart Failure','Hospitalization','Humans','Sodium-Glucose Transporter 2 Inhibitors','Stroke Volume','Ventricular Function, Left']::text[] WHERE doc_id='10.1038/s41591-021-01659-1';
UPDATE artigos SET mesh_terms=ARRAY['Acetazolamide','Acute Disease','Carbonic Anhydrase Inhibitors','Diuretics','Double-Blind Method','Heart Failure','Humans','Natriuretic Peptide, Brain','Sodium','Sodium Potassium Chloride Symporter Inhibitors','Stroke Volume','Symptom Flare Up','Treatment Outcome','Ventricular Function, Left','Water-Electrolyte Imbalance']::text[] WHERE doc_id='10.1056/NEJMoa2203094';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Female','Humans','Male','Middle Aged','Cardiotonic Agents','Chronic Disease','Digitoxin','Double-Blind Method','Follow-Up Studies','Heart Failure','Hospitalization','Kaplan-Meier Estimate','Stroke Volume','Disease Progression','Treatment Outcome']::text[] WHERE doc_id='10.1056/NEJMoa2415471';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Stroke Volume','Mineralocorticoid Receptor Antagonists','Practice Guidelines as Topic','Digitalis Glycosides']::text[] WHERE doc_id='10.1007/s10741-026-10609-3';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Benzhydryl Compounds','Creatinine','Diuresis','Diuretics','Glucosides','Heart Failure','Kidney','Prospective Studies','Sodium','Sodium Potassium Chloride Symporter Inhibitors','Sodium-Glucose Transporter 2 Inhibitors']::text[] WHERE doc_id='10.1161/CIRCULATIONAHA.122.059038';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Aged, 80 and over','Combined Modality Therapy','Female','Heart Failure','Heart Valve Prosthesis','Heart Valve Prosthesis Implantation','Hospitalization','Humans','Intention to Treat Analysis','Kaplan-Meier Estimate','Male','Middle Aged','Mitral Valve','Mitral Valve Insufficiency','Percutaneous Coronary Intervention','Prosthesis Failure','Stroke Volume','Treatment Outcome','Ventricular Dysfunction, Left']::text[] WHERE doc_id='10.1056/NEJMoa1805374';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Hydroxymethylglutaryl-CoA Reductase Inhibitors','Female','United States','Aged','American Heart Association','Male','Risk Assessment','Coronary Vessels','Coronary Artery Disease','Vascular Calcification','Middle Aged','Calcium']::text[] WHERE doc_id='10.1016/j.jacc.2026.05.039';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Anti-Arrhythmia Agents','Atrial Fibrillation','Catheter Ablation','Female','Follow-Up Studies','Heart Failure','Heart Rate','Hospitalization','Humans','Kaplan-Meier Estimate','Male','Middle Aged','Ventricular Function, Left','Walk Test']::text[] WHERE doc_id='10.1056/NEJMoa1707855';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Cardiac Pacing, Artificial','Cardiovascular Diseases','Death, Sudden, Cardiac','Defibrillators, Implantable','Electrocardiography','Female','Follow-Up Studies','Heart Failure, Systolic','Humans','Male','Middle Aged','Mortality','Stroke Volume']::text[] WHERE doc_id='10.1056/NEJMoa1608029';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Cardiovascular Diseases','Cause of Death','Combined Modality Therapy','Coronary Artery Bypass','Female','Follow-Up Studies','Heart Failure','Hospitalization','Humans','Kaplan-Meier Estimate','Male','Middle Aged','Myocardial Ischemia','Stroke Volume','Ventricular Dysfunction, Left']::text[] WHERE doc_id='10.1056/NEJMoa1602001';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Artificial Intelligence','Cicatrix','Prospective Studies','Magnetic Resonance Imaging, Cine','Female','Myocardial Infarction','Male','Contrast Media','Middle Aged','Myocardium','Image Enhancement']::text[] WHERE doc_id='10.1016/j.jacc.2026.05.029';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Aminobutyrates','Angiotensin Receptor Antagonists','Angiotensin-Converting Enzyme Inhibitors','Biphenyl Compounds','Double-Blind Method','Drug Combinations','Enalapril','Female','Heart Failure','Hospitalization','Humans','Kaplan-Meier Estimate','Male','Middle Aged','Neprilysin','Stroke Volume','Tetrazoles','Valsartan']::text[] WHERE doc_id='10.1056/NEJMoa1409077';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Aged, 80 and over','Cardiovascular Diseases','Double-Blind Method','Female','Follow-Up Studies','Heart Failure','Hospitalization','Humans','Incidence','Kaplan-Meier Estimate','Male','Middle Aged','Mineralocorticoid Receptor Antagonists','Spironolactone','Stroke Volume','Treatment Failure']::text[] WHERE doc_id='10.1056/NEJMoa1313731';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Ultrasonography, Interventional','Plaque, Atherosclerotic','Artificial Intelligence','Coronary Artery Disease','Coronary Vessels']::text[] WHERE doc_id='10.1002/clc.70423';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Aminobutyrates','Angioedema','Angiotensin Receptor Antagonists','Biphenyl Compounds','Cardiovascular Diseases','Double-Blind Method','Drug Combinations','Female','Follow-Up Studies','Heart Failure','Hospitalization','Humans','Hypotension','Male','Middle Aged','Neprilysin','Quality of Life','Sex Factors','Single-Blind Method','Stroke Volume','Tetrazoles','Valsartan']::text[] WHERE doc_id='10.1056/NEJMoa1908655';
UPDATE artigos SET mesh_terms=ARRAY['Acute Disease','Aged','Double-Blind Method','Dyspnea','Female','Heart Failure','Humans','Hypotension','Intention to Treat Analysis','Kidney Diseases','Male','Middle Aged','Natriuretic Agents','Natriuretic Peptide, Brain','Patient Readmission','Recurrence']::text[] WHERE doc_id='10.1056/NEJMoa1100171';
UPDATE artigos SET mesh_terms=ARRAY['Actuarial Analysis','Adult','Aged','Aged, 80 and over','Cause of Death','Female','Heart Failure','Heart-Assist Devices','Humans','Kaplan-Meier Estimate','Male','Middle Aged','Proportional Hazards Models','Prosthesis Design','Prosthesis Failure','Quality of Life','Stroke','Stroke Volume']::text[] WHERE doc_id='10.1056/NEJMoa0909938';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Electrocardiography','Female','Male','Artificial Intelligence','Aged','Aged, 80 and over','Heart Diseases','Echocardiography']::text[] WHERE doc_id='10.1016/j.jacc.2026.06.013';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Angioplasty, Balloon','Randomized Controlled Trials as Topic','Peripheral Arterial Disease','Amputation, Surgical','Lower Extremity','Ischemia','Popliteal Artery','Quality of Life','Vascular Patency','Intermittent Claudication']::text[] WHERE doc_id='10.1002/14651858.CD011319.pub3';
UPDATE artigos SET mesh_terms=ARRAY['Acute Coronary Syndrome','Aged','Angina, Unstable','Aspirin','Double-Blind Method','Drug Therapy, Combination','Factor Xa Inhibitors','Female','Hemorrhage','Humans','Kaplan-Meier Estimate','Male','Middle Aged','Myocardial Infarction','Platelet Aggregation Inhibitors','Proportional Hazards Models','Pyrazoles','Pyridones','Stroke','Treatment Outcome']::text[] WHERE doc_id='10.1056/NEJMoa1105819';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Aspirin','Atherosclerosis','Cardiovascular Diseases','Double-Blind Method','Drug Therapy, Combination','Factor Xa Inhibitors','Female','Hemorrhage','Humans','Male','Middle Aged','Platelet Aggregation Inhibitors','Rivaroxaban','Secondary Prevention']::text[] WHERE doc_id='10.1056/NEJMoa1709118';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Child','Randomized Controlled Trials as Topic','Exercise','Pediatric Obesity','Child, Preschool','Body Mass Index','Quality of Life','Bias','Female']::text[] WHERE doc_id='10.1002/14651858.CD015988';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Randomized Controlled Trials as Topic','Blood Pressure','Ischemic Stroke','Thrombolytic Therapy','Antihypertensive Agents','Thrombectomy','Hypertension','Stroke','Intracranial Hemorrhages']::text[] WHERE doc_id='10.1002/14651858.CD016085.pub2';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Male','Imidazoles','Female','Coronary Artery Disease','Gastrointestinal Microbiome','Middle Aged','Aged','Prospective Studies','Prognosis','Propionates','Cardiometabolic Risk Factors','Biomarkers','Acute Coronary Syndrome']::text[] WHERE doc_id='10.1093/eurheartj/ehaf661';
UPDATE artigos SET mesh_terms=ARRAY['Acute Disease','Aged','Aminobutyrates','Angiotensin Receptor Antagonists','Angiotensin-Converting Enzyme Inhibitors','Biphenyl Compounds','Cardiac Output, Low','Dose-Response Relationship, Drug','Double-Blind Method','Drug Combinations','Enalapril','Female','Heart Failure','Humans','Male','Middle Aged','Natriuretic Peptide, Brain','Neprilysin','Peptide Fragments','Stroke Volume','Tetrazoles','Valsartan']::text[] WHERE doc_id='10.1056/NEJMoa1812851';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Diabetes Mellitus, Type 2','Double-Blind Method','Glucagon-Like Peptides','Heart Failure','Obesity','Stroke Volume','Glucagon-Like Peptide-1 Receptor Agonists','Semaglutide']::text[] WHERE doc_id='10.1056/NEJMoa2313917';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Female','Humans','Male','Middle Aged','Coronary Artery Disease','Follow-Up Studies','Heart Failure','Phenotype','Polysomnography','Prevalence','Risk Factors','Severity of Illness Index','Sleep Apnea, Obstructive','Stroke Volume','Ventricular Function, Left','Randomized Controlled Trials as Topic','Clinical Trials, Phase IV as Topic']::text[] WHERE doc_id='10.1002/clc.70402';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Percutaneous Coronary Intervention','Tomography, Optical Coherence','Plaque, Atherosclerotic','Male','Female','Treatment Outcome','Coronary Artery Disease','Fibrosis','Predictive Value of Tests','Aged','Risk Factors','Time Factors','Coronary Vessels','Middle Aged','Vascular Calcification','Myocardial Infarction','Lipids','Multivariate Analysis','Coronary Angiography']::text[] WHERE doc_id='10.1016/j.jcmg.2026.05.015';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Defibrillators, Implantable','Benzhydryl Compounds','Death, Sudden, Cardiac','Female','Male','Sodium-Glucose Transporter 2 Inhibitors','Glucosides','Stroke Volume','Propensity Score','Aged','Middle Aged','Angiotensin-Converting Enzyme Inhibitors']::text[] WHERE doc_id='10.1016/j.jchf.2026.103166';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Cardiac Resynchronization Therapy','Defibrillators, Implantable','Heart Failure','Kaplan-Meier Estimate','Stroke Volume','Treatment Outcome','Ventricular Function, Left','Electrocardiography','Follow-Up Studies','Time Factors']::text[] WHERE doc_id='10.1056/NEJMoa2304542';
UPDATE artigos SET mesh_terms=ARRAY['Aged','Female','Humans','Male','Heart-Assist Devices','Incidence','Shock, Cardiogenic','ST Elevation Myocardial Infarction','Treatment Outcome','Assisted Circulation']::text[] WHERE doc_id='10.1056/NEJMoa2312572';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Male','Female','Brazil','Registries','Aged','Prospective Studies','Middle Aged','Acute Disease','Hospitalization','Treatment Outcome','Disease Management','Follow-Up Studies','Time Factors','Aged, 80 and over','Drug Monitoring']::text[] WHERE doc_id='10.1016/j.cardfail.2023.08.014';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Iron Deficiencies','Quality of Life','Stroke Volume','Ventricular Function, Left','Ferric Compounds','Double-Blind Method','Administration, Intravenous','Ambulatory Care','Maltose']::text[] WHERE doc_id='10.1056/NEJMoa2304968';
UPDATE artigos SET mesh_terms=ARRAY['Humans','Heart Failure','Percutaneous Coronary Intervention','Stroke Volume','Treatment Outcome','Ventricular Dysfunction, Left','Ventricular Function, Left','Coronary Artery Disease','Cardiovascular Agents','Myocardial Ischemia']::text[] WHERE doc_id='10.1056/NEJMoa2206606';

-- procurados e sem descritor no PubMed (artigo novo, sem DOI indexado):
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.vhri.2026.101666';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/eurheartj/ehaf190';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102933';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjvshd/xwag039';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102929';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2026.05.037';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1161/CIR.0000000000001454';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1136/heartjnl-2025-327651';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/eurheartj/ehag088';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjopen/oeag101';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/eurjpc/zwag313';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1161/CIR.0000000000001456';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.15420/cfr.2025.52';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1136/bmjmed-2022-000137';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1177/19322968241292041.118';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/eurjpc/zwag341';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.31661/gmj.v15i.4274';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjopen/oeag054';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102856';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jchf.2026.103111';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102962';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102744';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jaccao.2026.04.009';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102942';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103046';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103006';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103057';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102990';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjopen/oeag092';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102984';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjopen/oeag109';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1136/bmjph-2025-004599';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjopen/oeag076';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102982';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjopen/oeag095';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.ijcard.2026.134680';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102917';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102862';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jchf.2026.103218';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102864';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jchf.2026.103235';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102922';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jchf.2026.103239';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/eurheartj/ehag516';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.3389/fphar.2026.1800868';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2026.07.014';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1097/MCC.0000000000001409';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2026.07.005';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjopen/oeag067';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1007/s00467-026-07293-8';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1161/CIRCOUTCOMES.125.013063';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/jamacardio.2026.2226';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/jamacardio.2026.2546';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.3390/jcm15145343';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacep.2026.05.005';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.36660/abc.20250640';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjopen/oeag107';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1055/a-2787-0186';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.2174';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1161/CIRCULATIONAHA.126.081405';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jchf.2026.103283';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1136/heartjnl-2025-327623';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jaccao.2026.05.002';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/eurheartj/ehag113';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjvshd/xwag044';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjvshd/xwag047';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjvshd/xwag052';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjvshd/xwag055';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjopen/oeag084';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102919';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102890';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102921';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102869';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102880';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102863';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102870';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102860';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102882';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102858';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102865';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jcmg.2026.05.014';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/jama.2026.9268';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/jamacardio.2026.2314';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/jamacardio.2026.2510';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/jamacardio.2026.2435';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjopen/oeag119';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/jamacardio.2026.2389';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.numecd.2026.104859';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/jamaoncol.2026.2066';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjci/jeag006';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1161/CIRCIMAGING.125.018670';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/ehjci/jeaf246';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1056/NEJMoa2603649';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102943';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102965';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103035';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102969';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103019';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102968';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102985';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102981';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103042';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103058';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103071';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103077';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103041';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103049';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103030';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103004';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103010';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103068';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102975';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103031';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103033';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/jamacardio.2026.2413';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/jamacardio.2026.2779';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1136/lma-2025-000005';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2026.05.049';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2026.06.018';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1161/CIR.0000000000001461';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2026.07.004';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.2337/doci25-0008';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.htct.2026.106482';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102967';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.103016';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2026.06.004';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.ajpc.2026.101675';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/eurheartj/ehaf1038';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.3390/';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1001/';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2025.12.079';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2026.03.033';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1161/CIRCOUTCOMES.125.013159';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1161/CIRCULATIONAHA.126.079459';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/eurheartj/ehag584';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacadv.2026.102875';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1093/eurjpc/zwag267';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2026.06.015';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/S0140-';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1161/CIR.0000000000001459';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jacc.2026.07.009';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.jchf.2026.103242';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1016/j.obpill.2026.100288';
UPDATE artigos SET mesh_terms='{}'::text[] WHERE doc_id='10.1161/CIRCULATIONAHA.125.074482';

-- e o resto, que nunca teve DOI buscavel: array vazio, nunca NULL
UPDATE artigos SET mesh_terms='{}'::text[] WHERE mesh_terms IS NULL;

SELECT count(*) FILTER (WHERE mesh_terms IS NULL) AS nulos,
       count(*) FILTER (WHERE cardinality(mesh_terms)=0) AS vazios,
       count(*) FILTER (WHERE cardinality(mesh_terms)>0) AS com_descritor
FROM artigos;
COMMIT;
