-- Preenche o TEMA dos artigos que subiram sem ele (buraco de 17-19/Ago).
-- Gerado por scripts/csv_tema.py + conferência a mão do Dr. Eduardo.
-- Só toca onde tema IS NULL: nao sobrescreve nada que ja tenha valor.

BEGIN;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='eplerenone-a-selective-aldosterone-blocker-in-patients-with-left-ventricular-dys' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='a-clinical-trial-of-the-angiotensin-convertingenzyme-inhibitor-trandolapril-in-p' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='effect-of-captopril-on-mortality-and-morbidity-in-patients-with-left-ventricular' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1161/01.CIR.0000035653.72855.BF' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1093/eurheartj/ehi118' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1009540' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1009492' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='valsartan-captopril-or-both-in-myocardial-infarction-complicated-by-heart-failur' AND tema IS NULL;
UPDATE artigos SET tema='Cardiometabólica', tema_secundario='Miocardiopatias', tema_origem='llm' WHERE doc_id='10.1001/jama.2026.12038' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='the-effect-of-carvedilol-on-morbidity-and-mortality-in-patients-with-chronic-hea' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='effect-of-enalapril-on-survival-in-patients-with-reduced-left-ventricular-ejecti' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1808848' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1001/' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='effects-of-enalapril-on-mortality-in-severe-congestive-heart-failure-results-of' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2022190' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2025797' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2107038' AND tema IS NULL;
UPDATE artigos SET tema='UTI Cardiológica', tema_secundario='Aorta/Congênitas/Genética', tema_origem='llm' WHERE doc_id='10.1161/STR.0000000000000513' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='the-cardiac-insufficiency-bisoprolol-study-ii-cibis-ii-a-randomised-trial' AND tema IS NULL;
UPDATE artigos SET tema='Cardiometabólica', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1161/CIR.0000000000001423' AND tema IS NULL;
UPDATE artigos SET tema='Hipertensão/HAS', tema_secundario='Aorta/Congênitas/Genética', tema_origem='llm' WHERE doc_id='10.1161/HYPERTENSIONAHA.125.25633' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2206286' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2410027' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2407107' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Hipertensão/HAS', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa0805450' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='prophylactic-use-of-an-implantable-cardioverterdefibrillator-after-acute-myocard' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='prophylactic-use-of-implanted-cardiac-defibrillators-in-patients-at-high-risk-fo' AND tema IS NULL;
UPDATE artigos SET tema='UTI Cardiológica', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMra2506111' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='10.1161/CIRCRESAHA.126.328602' AND tema IS NULL;
UPDATE artigos SET tema='Intervenção/Hemodinâmica', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1093/eurheartj/ehag334' AND tema IS NULL;
UPDATE artigos SET tema='Hipertensão/HAS', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1161/HYPERTENSIONAHA.126.26095' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='10.1056/NEJMra2415650' AND tema IS NULL;
UPDATE artigos SET tema='UTI Cardiológica', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1016/j.iac.2026.01.007' AND tema IS NULL;
UPDATE artigos SET tema='Aorta/Congênitas/Genética', tema_secundario='Imagem Cardiovascular', tema_origem='llm' WHERE doc_id='10.1161/CIRCULATIONAHA.125.077491' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Insuficiência Cardíaca', tema_origem='llm' WHERE doc_id='a-comparison-of-antiarrhythmic-drug-therapy-with-implantable-defibrillators-in-p' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa0906431' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa0908355' AND tema IS NULL;
UPDATE artigos SET tema='Cardiometabólica', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1016/j.jacc.2025.12.079' AND tema IS NULL;
UPDATE artigos SET tema='Miocardiopatias', tema_secundario='Imagem Cardiovascular', tema_origem='llm' WHERE doc_id='10.1016/j.jacc.2026.03.033' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1161/CIRCOUTCOMES.125.013159' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Imagem Cardiovascular', tema_origem='llm' WHERE doc_id='10.1161/CIRCULATIONAHA.126.079459' AND tema IS NULL;
UPDATE artigos SET tema='Cardiometabólica', tema_secundario='Hipertensão/HAS', tema_origem='llm' WHERE doc_id='10.1161/CIRCULATIONAHA.125.077666' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1161/CIRCOUTCOMES.125.013063' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1093/eurheartj/ehag584' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Insuficiência Cardíaca', tema_origem='llm' WHERE doc_id='10.1016/j.jacep.2026.01.037' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Intervenção/Hemodinâmica', tema_origem='llm' WHERE doc_id='10.1093/eurheartj/ehag113' AND tema IS NULL;
UPDATE artigos SET tema='UTI Cardiológica', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1093/eurheartj/ehag164' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Insuficiência Cardíaca', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1100356' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Valvulopatias', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1806640' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='UTI Cardiológica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1900486' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1016/j.jacadv.2026.102875' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1038/s41591-021-01659-1' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2203094' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1093/eurjpc/zwag267' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2415471' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Insuficiência Cardíaca', tema_origem='llm' WHERE doc_id='prophylactic-implantation-of-a-defibrillator-in-patients-with-myocardial-infarct' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='amiodarone-or-an-implantable-cardioverterdefibrillator-for-congestive-heart-fail' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='the-effect-of-cardiac-resynchronization-on-morbidity-and-mortality-in-heart-fail' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Insuficiência Cardíaca', tema_origem='llm' WHERE doc_id='prognostic-importance-of-defibrillator-shocks-in-patients-with-heart-failure' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='effect-of-vasodilator-therapy-on-mortality-in-chronic-congestive-heart-failure-r' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Valvulopatias', tema_origem='llm' WHERE doc_id='10.1007/s10741-026-10609-3' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1016/j.jacep.2026.01.011' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1016/j.jacc.2026.06.015' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1161/CIRCULATIONAHA.122.059038' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Valvulopatias', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1805374' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='the-effect-of-digoxin-on-mortality-and-morbidity-in-patients-with-heart-failure' AND tema IS NULL;
UPDATE artigos SET tema='Cardiometabólica', tema_secundario='Imagem Cardiovascular', tema_origem='llm' WHERE doc_id='10.1016/j.jacc.2026.05.039' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Insuficiência Cardíaca', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1707855' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Insuficiência Cardíaca', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1608029' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Miocardiopatias', tema_origem='llm' WHERE doc_id='prophylactic-defibrillator-implantation-in-patients-with-nonischemic-dilated-car' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='combination-of-isosorbide-dinitrate-and-hydralazine-in-blacks-with-heart-failure' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1602001' AND tema IS NULL;
UPDATE artigos SET tema='Imagem Cardiovascular', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1016/j.jacc.2026.05.029' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='sudden-death-in-patients-with-myocardial-infarction-and-left-ventricular-dysfunc' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Insuficiência Cardíaca', tema_origem='llm' WHERE doc_id='effects-of-losartan-and-captopril-on-mortality-and-morbidity-in-high-risk-patien' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='prophylactic-catheter-ablation-for-the-prevention-of-defibrillator-therapy' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Insuficiência Cardíaca', tema_origem='llm' WHERE doc_id='rhythm-control-versus-rate-control-for-atrial-fibrillation-and-heart-failure' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='effects-of-candesartan-in-patients-with-chronic-heart-failure-and-preserved-left' AND tema IS NULL;
UPDATE artigos SET tema='Arritmias/Anticoagulantes', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='defibrillator-implantation-early-after-myocardial-infarction' AND tema IS NULL;
UPDATE artigos SET tema='Cardiometabólica', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1161/JAHA.125.041495' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='diuretic-strategies-in-patients-with-acute-decompensated-heart-failure' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Hipertensão/HAS', tema_origem='llm' WHERE doc_id='10.1016/S0140-' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Hipertensão/HAS', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1409077' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='10.1161/CIR.0000000000001459' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='effects-of-exercise-training-on-health-status-in-patients-with-chronic-heart-fai' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1313731' AND tema IS NULL;
UPDATE artigos SET tema='Intervenção/Hemodinâmica', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1002/clc.70423' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1908655' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1100171' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='UTI Cardiológica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa0909938' AND tema IS NULL;
UPDATE artigos SET tema='Imagem Cardiovascular', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1016/j.jacc.2026.06.013' AND tema IS NULL;
UPDATE artigos SET tema='Intervenção/Hemodinâmica', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1002/14651858.CD011319.pub3' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1016/j.jacc.2026.07.009' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1105819' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1709118' AND tema IS NULL;
UPDATE artigos SET tema='Cardiometabólica', tema_secundario='Aorta/Congênitas/Genética', tema_origem='llm' WHERE doc_id='10.1002/14651858.CD015988' AND tema IS NULL;
UPDATE artigos SET tema='UTI Cardiológica', tema_secundario='Hipertensão/HAS', tema_origem='llm' WHERE doc_id='10.1002/14651858.CD016085.pub2' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1093/eurheartj/ehaf661' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa1812851' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2313917' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1002/clc.70402' AND tema IS NULL;
UPDATE artigos SET tema='Intervenção/Hemodinâmica', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1016/j.jcmg.2026.05.015' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Imagem Cardiovascular', tema_origem='llm' WHERE doc_id='10.1016/j.jchf.2026.103242' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='10.1016/j.jchf.2026.103166' AND tema IS NULL;
UPDATE artigos SET tema='Cardiometabólica', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1161/JAHA.125.046167' AND tema IS NULL;
UPDATE artigos SET tema='Cardiometabólica', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1016/j.obpill.2026.100288' AND tema IS NULL;
UPDATE artigos SET tema='Coronária/DAC', tema_secundario='Cardiometabólica', tema_origem='llm' WHERE doc_id='10.1161/CIRCULATIONAHA.125.074482' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2304542' AND tema IS NULL;
UPDATE artigos SET tema='UTI Cardiológica', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2312572' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1016/j.cardfail.2023.08.014' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2304968' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Coronária/DAC', tema_origem='llm' WHERE doc_id='10.1056/NEJMoa2206606' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Arritmias/Anticoagulantes', tema_origem='llm' WHERE doc_id='cardiac-resynchronization-in-chronic-heart-failure' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='Não se aplica', tema_origem='llm' WHERE doc_id='chronic-heart-failure-in-adults-diagnosis-and-management-ng106' AND tema IS NULL;
UPDATE artigos SET tema='Insuficiência Cardíaca', tema_secundario='UTI Cardiológica', tema_origem='llm' WHERE doc_id='10.1016/j.clnu.2026.106622' AND tema IS NULL;

-- confira ANTES do COMMIT:
SELECT count(*) FILTER (WHERE tema IS NULL) AS ainda_sem_tema, count(*) AS total FROM artigos;
COMMIT;
